git_url: https://github.com/rahulkj/tap-tools-image
git_branch: main
pivnet_token: ((pivnet_token))
docker_hub_repository: rjain/tap-tools-image

internal_registry:
  host: ((harbor_host))
  username: ((harbor_credentials.username))
  password: ((harbor_credentials.password))

tap:
  version: 1.12.1